spring:
  application:
    name: spring-ai-mcp-server

  ai:
    mcp:
      server:
        name: my-mcp-server
#        stdio: true
        type: sync
        annotation-scanner:
          enabled: true
        protocol: STREAMABLE

logging:
  level:
    org: DEBUG