spring:
  application:
    name: spring-ai-mcp-server
  ai:
    mcp:
      server:
        request-timeout: 5000
        name: spring-ai-mcp-server
#        stdio: true
        type: SYNC
        annotation-scanner:
          enabled: true
        protocol: STREAMABLE

logging:
  level:
    org: DEBUG

app:
  config: "{name: 'Hello App', version: 'v1.0.0'}"
  boolconfig: "{isEnabled: true}"